### PR TITLE
Update Webpack.md

### PR DESCRIPTION
**Pull request by dasDaniel**
Added `vue-loader` requirement

### CODE REVIEW

**Comment by rafaesc** [comment]
Thanks @dasDaniel

**Comment by elevatebart** [comment]
I do not understand why danger is not finding the token I gave it.
I will investigate.

**Comment by elevatebart** [comment]
OK my bad @rafaesc I made the TOKEN hidden, as I thought it should not be public but it seems that travis thinks it is a security issue. It makes sense...

Ooops.
Can you please create another token with the bot and set it as public key in travis?
thank you.

https://docs.travis-ci.com/user/pull-requests/#Pull-Requests-and-Security-Restrictions

**Comment by rafaesc** [comment]
Ok I will do

**Pull request merged**
