### PR TITLE
fix(vue-docgen-api): make doc defineExpose  working

### PR DESCRIPTION
**Pull request by chenjuneking**
In Vue3, expose properties by using `defineExpose()` API, not `defineExposed()`, and an `exposes` meta should be in the results.

```html
<script setup lang="ts">
function foo() { return 'bar' }
defineExpose({
  /**
   * Expose foo function
   *
   * @returns {string} The result of execute foo
   */
  foo,
})
</script>
```

output:
```js
{
  // ...
  exposes: [{
    description: 'Expose foo function',
    name: 'foo',
    tags: [ ... ],
  }],
}
```

### CODE REVIEW

**Comment by elevatebart** [comment]
I will also try to add support for the options API version of this once it's merged.

```js
export default {
  expose: [
    /**
     * Expose foo function
     *
     * @returns {string} The result of execute foo
     */
    'publicMethod'
  ],
  methods: {
    publicMethod() {
      // ...
    },
  }
}
```

**Comment by elevatebart** [comment]
Thank you so much for the good work. One last stretch before I can deliver it.

Can you run `pnpm install && pnpm test:vitest run -u` to update the test snapshots? 
If you need to install pnpm you can do it right from `npm install --global pnpm`.

**Comment by chenjuneking** [comment]
> 

sorry I ran the command but got failed:

```sh
$ git log -3
commit 55c1149e7bc2824060641440ef106a18df7be74d (HEAD -> fix/vue-docgen-api/expose, upstream/fix/vue-docgen-api/expose)
Author: elevatebart <ledouxb@gmail.com>
Date:   Thu Jul 28 21:39:04 2022 -0500

    update snapshots with exposed

commit 8cd064389b514ef7951bdc52bfee7003ac1bf3ed (origin/fix/vue-docgen-api/expose)
Merge: 6edb288b 594282bb
Author: Barthélémy Ledoux <ledouxb@gmail.com>
Date:   Thu Jul 28 21:28:30 2022 -0500

    Merge branch 'dev' into fix/vue-docgen-api/expose

commit 594282bb29ab7dc91d4644171ea43094388cece2 (upstream/dev)
Author: elevatebart <ledouxb@gmail.com>
Date:   Thu Jul 28 20:27:33 2022 -0500

    fix nuxtjs example

86185@j MINGW64 /d/projects/iopen/vue-styleguidist (fix/vue-docgen-api/expose)
$ pnpm install && pnpm test:vitest run -u
Scope: all 33 workspace projects
Lockfile is up-to-date, resolution step is skipped
Already up-to-date
packages/vue-inbrowser-compiler-demi postinstall$ node ./postinstall.js
└─ Done in 100ms
. postinstall$ pnpm compile
│ > @ compile D:\projects\iopen\vue-styleguidist
│ > pnpm recursive run compile
│ Scope: 32 of 33 workspace projects
│ packages/vue-inbrowser-compiler-utils compile$ rollup -c
│ packages/vue-inbrowser-compiler-utils compile:
│ packages/vue-inbrowser-compiler-utils compile: D:\projects\iopen\vue-styleguidist\packages\vue-inbrowser-compiler-utils\src\index.ts → lib/vu
│ packages/vue-inbrowser-compiler-utils compile: created lib/vue-inbrowser-compiler-utils.cjs.js, lib/vue-inbrowser-compiler-utils.esm.js in 1.
│ packages/vue-inbrowser-compiler-utils compile: Done
│ packages/vue-docgen-api compile$ tsc -p ./tsconfig.build.json
│ packages/vue-inbrowser-compiler compile$ rollup -c
│ packages/vue-inbrowser-compiler-sucrase compile$ rollup -c
│ packages/vue-inbrowser-compiler compile: 
│ packages/vue-inbrowser-compiler compile: D:\projects\iopen\vue-styleguidist\packages\vue-inbrowser-compiler\src\index.ts → lib/vue-inbrowser-
│ packages/vue-inbrowser-compiler-sucrase compile: 
│ packages/vue-inbrowser-compiler-sucrase compile: D:\projects\iopen\vue-styleguidist\packages\vue-inbrowser-compiler-sucrase\src\index.ts → li
│ packages/vue-inbrowser-compiler-sucrase compile: created lib/vue-inbrowser-compiler-sucrase.cjs.js, lib/vue-inbrowser-compiler-sucrase.esm.js
│ packages/vue-inbrowser-compiler-sucrase compile: Done
│ packages/vue-inbrowser-compiler compile: created lib/vue-inbrowser-compiler.cjs.js, lib/vue-inbrowser-compiler.esm.js in 2.4s
│ packages/vue-inbrowser-compiler compile: Done
│ packages/vue-docgen-api compile: Done
│ packages/vue-docgen-cli compile$ tsc -p ./tsconfig.build.json
│ packages/vue-styleguidist compile$ pnpm run compile:babel && pnpm run typings
│ packages/vue-styleguidist compile: > vue-styleguidist@4.48.0 compile:babel D:\projects\iopen\vue-styleguidist\packages\vue-styleguidist
│ packages/vue-styleguidist compile: > babel --delete-dir-on-start src/ --ignore **/__tests__,**/*.spec.* -d lib/ --extensions .js,.ts,.tsx,.js
│ packages/vue-styleguidist compile: Successfully compiled 121 files with Babel (2671ms).
│ packages/vue-styleguidist compile: > vue-styleguidist@4.48.0 typings D:\projects\iopen\vue-styleguidist\packages\vue-styleguidist
│ packages/vue-styleguidist compile: > tsc --emitDeclarationOnly -p ./tsconfig.build.json
│ packages/vue-styleguidist compile: src/client/rsg-components/Argument/ArgumentRenderer.tsx(43,4): error TS2786: 'Group' cannot be used as a J
│ packages/vue-styleguidist compile:   Its return type 'ReactElement<any, any> | null' is not a valid JSX element.
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element'.
│ packages/vue-styleguidist compile: src/client/rsg-components/Argument/ArgumentRenderer.tsx(47,7): error TS2786: 'Name' cannot be used as a JS
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<NameProps, "children" | "deprecated">, any, an
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/Argument/ArgumentRenderer.tsx(52,6): error TS2786: 'Type' cannot be used as a JS
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<TypeProps, "children">, any, any> | null' is n
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/Argument/ArgumentRenderer.tsx(59,21): error TS2786: 'Markdown' cannot be used as
│ packages/vue-styleguidist compile:   Its return type 'ReactElement<any, any> | null' is not a valid JSX element.
│ packages/vue-styleguidist compile: src/client/rsg-components/Arguments/ArgumentsRenderer.tsx(37,7): error TS2786: 'Heading' cannot be used as
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<HeadingProps, "lang" | "title" | "color" | "tr
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/Arguments/ArgumentsRenderer.tsx(41,6): error TS2786: 'Argument' cannot be used a
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Omit<ArgumentPropsWithClasses, "classes">, any, any
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/JsDoc/JsDoc.tsx(63,29): error TS2786: 'SubComponents' cannot be used as a JSX co
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Omit<SubComponentsProps & JssInjectedProps, "classe
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/JsDoc/JsDoc.tsx(67,8): error TS2786: 'Argument' cannot be used as a JSX componen
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Omit<ArgumentPropsWithClasses, "classes">, any, any
│ packages/vue-styleguidist compile: src/client/rsg-components/JsDoc/JsDoc.tsx(85,9): error TS2786: 'Markdown' cannot be used as a JSX componen
│ packages/vue-styleguidist compile:   Its return type 'ReactElement<any, any> | null' is not a valid JSX element.
│ packages/vue-styleguidist compile: src/client/rsg-components/Methods/MethodsRenderer.tsx(18,10): error TS2786: 'Name' cannot be used as a JSX
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<NameProps, "children" | "deprecated">, any, an
│ packages/vue-styleguidist compile: src/client/rsg-components/Methods/MethodsRenderer.tsx(27,8): error TS2786: 'Markdown' cannot be used as a 
│ packages/vue-styleguidist compile:   Its return type 'ReactElement<any, any> | null' is not a valid JSX element.
│ packages/vue-styleguidist compile: src/client/rsg-components/Methods/MethodsRenderer.tsx(33,8): error TS2786: 'Argument' cannot be used as a 
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Omit<ArgumentPropsWithClasses, "classes">, any, any
│ packages/vue-styleguidist compile: src/client/rsg-components/Methods/MethodsRenderer.tsx(41,6): error TS2786: 'JsDoc' cannot be used as a JSX
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Omit<TagProps & JssInjectedProps, "classes">, any, 
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/Methods/MethodsRenderer.tsx(49,4): error TS2786: 'Arguments' cannot be used as a
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Omit<ArgumentsProps, "classes">, any, any> | null' 
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/Methods/MethodsRenderer.tsx(84,10): error TS2786: 'Table' cannot be used as a JS
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<TableProps, "columns" | "rows" | "getRowKey">,
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/SectionHeading/SectionHeading.tsx(35,4): error TS2786: 'SectionHeadingRenderer' 
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Omit<SectionHeadingRendererProps, "classes">, any, 
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/SectionHeading/SectionHeadingRenderer.tsx(71,5): error TS2786: 'Heading' cannot 
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<HeadingProps, "lang" | "title" | "color" | "tr
│ packages/vue-styleguidist compile: src/client/rsg-components/slots/CodeTabButton.tsx(11,55): error TS2786: 'TabButton' cannot be used as a JS
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<TabButtonProps, "name" | "children" | "classNa
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/slots/IsolateButton.tsx(17,4): error TS2786: 'ToolbarButton' cannot be used as a
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<ToolbarButtonProps, "href" | "title" | "small"
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile:       Type 'ReactElement<any, any>' is missing the following properties from type 'Element': isRootInsert,
│ packages/vue-styleguidist compile: src/client/rsg-components/slots/IsolateButton.tsx(25,4): error TS2786: 'ToolbarButton' cannot be used as a
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<ToolbarButtonProps, "href" | "title" | "small"
│ packages/vue-styleguidist compile: src/client/rsg-components/slots/UsageTabButton.tsx(36,4): error TS2786: 'TabButton' cannot be used as a JS
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<TabButtonProps, "name" | "children" | "classNa
│ packages/vue-styleguidist compile: src/client/rsg-components/StyleguideFooter/StyleguideFooterRenderer.tsx(27,5): error TS2786: 'Markdown' ca
│ packages/vue-styleguidist compile:   Its return type 'ReactElement<any, any> | null' is not a valid JSX element.
│ packages/vue-styleguidist compile: src/client/rsg-components/SubComponents/SubComponents.tsx(61,6): error TS2786: 'Link' cannot be used as a 
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<LinkProps, "href" | "target" | "children" | "c
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/VsgArgument/ArgumentRenderer.tsx(42,4): error TS2786: 'Group' cannot be used as 
│ packages/vue-styleguidist compile:   Its return type 'ReactElement<any, any> | null' is not a valid JSX element.
│ packages/vue-styleguidist compile: src/client/rsg-components/VsgArgument/ArgumentRenderer.tsx(46,7): error TS2786: 'Name' cannot be used as a
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<NameProps, "children" | "deprecated">, any, an
│ packages/vue-styleguidist compile: src/client/rsg-components/VsgArgument/ArgumentRenderer.tsx(51,6): error TS2786: 'Type' cannot be used as a
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<Pick<TypeProps, "children">, any, any> | null' is n
│ packages/vue-styleguidist compile: src/client/rsg-components/VsgArgument/ArgumentRenderer.tsx(58,21): error TS2786: 'Markdown' cannot be used
│ packages/vue-styleguidist compile:   Its return type 'ReactElement<any, any> | null' is not a valid JSX element.
│ packages/vue-styleguidist compile: src/client/rsg-components/VsgEditor/EditorPrism.tsx(174,10): error TS2786: 'PEditor' cannot be used as a J
│ packages/vue-styleguidist compile:   Its element type 'ReactElement<any, any> | Component<UnconfiguredEditorProps, any, any> | null' is not a
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, any>' is not assignable to type 'Element | ElementClass | null'.
│ packages/vue-styleguidist compile: src/client/rsg-components/VsgReactComponent/ReactComponent.tsx(64,6): error TS2786: 'DocumentedComponentCo
│ packages/vue-styleguidist compile:   Its return type 'ReactElement<any, string | JSXElementConstructor<any>> | null' is not a valid JSX eleme
│ packages/vue-styleguidist compile: src/client/rsg-components/VsgReactComponent/ReactComponent.tsx(75,10): error TS2786: 'DocumentedComponentC
│ packages/vue-styleguidist compile:   Its return type 'ReactElement<any, string | JSXElementConstructor<any>> | null' is not a valid JSX eleme
│ packages/vue-styleguidist compile: src/client/utils/renderStyleguide.tsx(59,4): error TS2786: 'RenderJsxContext.Provider' cannot be used as a
│ packages/vue-styleguidist compile:   Its return type 'ReactElement<any, string | JSXElementConstructor<any>> | null' is not a valid JSX eleme
│ packages/vue-styleguidist compile:     Type 'ReactElement<any, string | JSXElementConstructor<any>>' is missing the following properties from
│ packages/vue-styleguidist compile: src/client/utils/renderStyleguide.tsx(60,5): error TS2786: 'StyleGuide' cannot be used as a JSX component.
│ packages/vue-styleguidist compile:   Its instance type 'StyleGuide' is not a valid JSX element.
│ packages/vue-styleguidist compile:     Property '$props' is missing in type 'StyleGuide' but required in type 'ElementClass'.
│ packages/vue-styleguidist compile:  ELIFECYCLE  Command failed with exit code 2.
│ packages/vue-styleguidist compile: Failed
│ undefined
│ D:\projects\iopen\vue-styleguidist\packages\vue-styleguidist:
│  ERR_PNPM_RECURSIVE_RUN_FIRST_FAIL  vue-styleguidist@4.48.0 compile: `pnpm run compile:babel && pnpm run typings`
│ Exit status 1
│  ELIFECYCLE  Command failed with exit code 1.
└─ Failed in 14.7s
 ELIFECYCLE  Command failed with exit code 1.
```

**Comment by chenjuneking** [comment]
I had finished an alpha version of styleguidist-like project base on [vitepress](https://github.com/vuejs/vitepress), there's a huge changes compared with this project, and I think there's more close to the Vue eco system(both of the components and styleguidist are using vite.js). Looking forward to this patch for my next development;)

**Comment by elevatebart** [comment]
That's exciting !!!

Can't wait to take this new tool for a spin!

I am going to merge this pR and fix the snapshot in the main repo. It will take me 5 min.

**Comment by chenjuneking** [comment]
> That's exciting !!!
> 
> Can't wait to take this new tool for a spin!
> 
> I am going to merge this pR and fix the snapshot in the main repo. It will take me 5 min.

Thanks for the great job!!!
I found that the version of vue-docgen-api was v4.47.1 on github, but still v4.47.0 on NPM, when does this version will be ready on NPM? Looking forward of that.

**Comment by elevatebart** [comment]
struggling with CI...

**Comment by lichangwei** [comment]
Awesome, I Can't wait to use the new version.

**Comment by chenjuneking** [comment]
Unable to clone / pull / push from github, because of Nancy Pelosi's special journey...

**Comment by elevatebart** [comment]
That's no fun for sure...

**Comment by chenjuneking** [comment]
> I had finished an alpha version of styleguidist-like project base on [vitepress](https://github.com/vuejs/vitepress), there's a huge changes compared with this project, and I think there's more close to the Vue eco system(both of the components and styleguidist are using vite.js). Looking forward to this patch for my next development;)

I'd uploaded the source code, I think it's far different from this project so I didn't send a pull request.
I think some points that can be improved in the future(maybe):

- The sandbox implement(now is using iframe)
- The editor(now is AMD implement)

you could visit the project via [this link](https://github.com/chenjuneking/vite-styleguidist).

**Comment by elevatebart** [comment]
@chenjuneking I really like the iframe implementation.

I would love with your permission to integrate the concept into the next major version of vue-live@3.

Iframe used to be super bad for performance. 
I guess if we only render them when they scroll into view this could be a great way to show components behavior in a context, without leaks and with media query responsive design.

What do you think?

**Comment by chenjuneking** [comment]
> @chenjuneking I really like the iframe implementation.
> 
> 
> 
> I would love with your permission to integrate the concept into the next major version of vue-live@3.
> 
> 
> 
> Iframe used to be super bad for performance. 
> 
> I guess if we only render them when they scroll into view this could be a great way to show components behavior in a context, without leaks and with media query responsive design.
> 
> 
> 
> What do you think?

That's a nice idea, looking forward the next version.

**Pull request merged**
