### PR TITLE
Allow for multiple @fires doclets for events

### PR DESCRIPTION
**Pull request by StotoV**
Previously it was not possible to have multiple events linked to a single
function with the @fires doclet. This commit allows this. The tests might
not be working correctly.

Extends #836

### CODE REVIEW

**Comment by StotoV** [comment]
I unfortunately did not get the toolchain to work locally, so I was unable to actually test the code. I have made the same change in the compiled javascript code locally and that worked fine. This is the non-verified typescript conversion.

**Comment by elevatebart** [comment]
Hello @StotoV, Thank you for this PR.

Great to see your work on this. 
It seems you scratching an itch that you need; this is exactly how we keep a library alive.

One remark:
Do you know how an event can have a payload (arguments)?

In this case, `$emit` can be called with the syntax below.

```js
this.$emit('change', {what:1, has:2, changed:3}, hasChanged)
```

WIth the multiple `@fires` in the same block syntax, how would you go about documenting the payload of the event?

Regarding the toolchain, I have not tried it on windows recently so it might need fixing. Let me check that.

What version of node/OS/package manager are you using?

**Comment by StotoV** [comment]
Thank you for the quick response @elevatebart! Having this minor change will indeed be a very nice improvement for our documentation!

As for the question I think I do not quite get what you mean. As I understand it you can create a doctag for each event and use the `@fires ` tag to signal which events can be emitted in a function. I do use the `@properties` tag for the event a bit different than is intended, documenting the channel where the event is emitted and whether it listens to a channel or outputs on a channel. E.g.
```vue
/**
 * Enable confirmation modal
 *
 * @event Enable
 * @property {channel} - modal_channel
 * @property {type} - emit
 */
/**
 * Execute payload upon receiving this event
 *
 * @event Confirm
 * @property {channel} - modal_channel
 * @property {type} - on
 */
/** 
 * @fires Enable
 * @fires Confirm
 */
click() {
   // ...
        EventBus.$emit(this.modal_channel, 'Enable')
        EventBus.$on(this.modal_channel, (payload) => { if (payload == 'Confirm') this.action() })
   // ...
}
```

The reason I proposed the current modification is that I have to rely on the `@fires` tag as I use the EventBus pattern and I could otherwise not get the events to appear in the documentation. Having this change would make it workable in a neat way.

For getting the toolchain to work; I have to confess I only tried running the `npm install` command and did not dig in when it did not immediately work out of the box. I am currently running the following system:
```bash
$ cat /etc/*release
DISTRIB_ID="Arch"
DISTRIB_RELEASE="rolling"
...
```
``` bash
$ npm --version
8.1.0
```
```bash
$ node --version
v16.13.0
```
When running some of the commands provided in the `package.json` I get the following output:
```bash
$ npm run pretest

> pretest
> pnpm lint


> @ lint /home/tom/Documents/Developer/Open Source/vue-styleguidist
> eslint . --cache --fix --ext .ts,.tsx,.js --cache-location node_modules/.eslint_cache/


Oops! Something went wrong! :(

ESLint: 7.32.0

Error: Failed to load parser 'babel-eslint' declared in '.eslintrc': Cannot find module 'babel-eslint'
Require stack:
- /home/tom/Documents/Developer/Open Source/vue-styleguidist/.eslintrc
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.resolve (node:internal/modules/cjs/helpers:108:19)
    at Object.resolve (/home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/@eslint/eslintrc/lib/shared/relative-module-resolver.js:28:50)
    at ConfigArrayFactory._loadParser (/home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/@eslint/eslintrc/lib/config-array-factory.js:929:45)
    at ConfigArrayFactory._normalizeObjectConfigDataBody (/home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/@eslint/eslintrc/lib/config-array-factory.js:724:43)
    at _normalizeObjectConfigDataBody.next (<anonymous>)
    at ConfigArrayFactory._normalizeObjectConfigData (/home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/@eslint/eslintrc/lib/config-array-factory.js:665:20)
    at _normalizeObjectConfigData.next (<anonymous>)
    at ConfigArrayFactory.loadInDirectory (/home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/@eslint/eslintrc/lib/config-array-factory.js:511:28)
    at CascadingConfigArrayFactory._loadConfigInAncestors (/home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/@eslint/eslintrc/lib/cascading-config-array-factory.js:379:46)
 ELIFECYCLE  Command failed with exit code 2.
```
```bash
$ npm run build
> build
> ./start.sh build


> vue-styleguidist-example-basic@4.0.0 styleguide:build
> vue-styleguidist build

Error: Cannot find module 'vue/compiler-sfc'
Require stack:
- /home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/vue-loader/dist/index.js
- /home/tom/Documents/Developer/Open Source/vue-styleguidist/examples/basic/styleguide.config.js
- /home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/vue-styleguidist/lib/scripts/config.js
- /home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/vue-styleguidist/lib/bin/styleguidist.js
- /home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/vue-styleguidist/lib/bin.js
Error: Cannot find module 'vue/compiler-sfc'
Require stack:
- /home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/vue-loader/dist/index.js
- /home/tom/Documents/Developer/Open Source/vue-styleguidist/examples/basic/styleguide.config.js
- /home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/vue-styleguidist/lib/scripts/config.js
- /home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/vue-styleguidist/lib/bin/styleguidist.js
- /home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/vue-styleguidist/lib/bin.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/tom/Documents/Developer/Open Source/vue-styleguidist/node_modules/vue-loader/dist/index.js:8:24)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/tom/Documents/Developer/Open Source/vue-styleguidist/examples/basic/styleguide.config.js:2:19)
    at Module._compile (node:internal/modules/cjs/loader:1101:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1153:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
```
So the errors are mostly missing packages that do not appear to install correctly or are missing in the package.json. If you have any pointers let me know! Though I will probably give it an actual good try sometime later this week.

**Comment by elevatebart** [comment]
Thank you @StotoV. This explanation is very clear and we will get you sorted out.

Vue-styleguidist repository relies on [pnpm](https://github.com/pnpm/pnpm)
If you wish to run the tests, run the following:

install pnpm (this gets your packages installed fairly faster)
```sh
npm install --global pnpm
``` 

then install the packages
```sh
pnpm install
```

and finally you can run the tests
```sh
pnpm test:jest
```

If you wish to update the snapshots, run with the -u
```sh
pnpm test:jest -- -u
```

Your use case is not very common. 
I would prefer it if it did not change the nature of the current output for common use cases.
If it does, it's a breaking change and will require a new major version.
I plan on getting o few breaking changes at once and it will be a while until I create a new stable major version.

Could you also add a new changeset using the command below to explain the changes to whomever wants to observe your changes?

```sh
pnpx changeset
```

Thank you so much.

**Comment by elevatebart** [comment]
delivered in [vue-docgen-api@4.47.0](https://github.com/vue-styleguidist/vue-styleguidist/releases/tag/vue-docgen-api%404.47.0)

**Comment by elevatebart** [comment]
fixed by https://github.com/vue-styleguidist/vue-styleguidist/pull/1328

**Pull request closed without merging**
