### PR TITLE
Single File Component Format: add support for <style scoped>

### PR DESCRIPTION
**Pull request by mrjones2014**
add support for the `<style scoped>` tag in the single file component format

### CODE REVIEW

**Comment by rafaesc** [comment]
Amazing job!

Thanks for the PR, can you add a documentation of this feature, on this page?

https://github.com/vue-styleguidist/vue-styleguidist/blob/master/docs/Documenting.md#usage-examples-and-readme-files

Regards!

**Comment by mrjones2014** [comment]
@rafaesc  added the requested documentation!

**Comment by rafaesc** [comment]
Thank @mrjones2014 

I will review it

**Comment by rafaesc** [comment]
Awesome job,

only I added scopeId to add the classname respectly the easier


image

**Comment by nicooprat** [comment]
Looks like scoped attribute messes with `before/after` pseudo selectors, here's what is output:

```html
<style data-cssscoper="true">
.wrapper[data-v-2011] {
  background-color: red;
}
.wrapper:before[data-v-2011] {
  content: '';
}
</style>
```

The second selector should be:

```css
.wrapper[data-v-2011]:before
```

Did I miss something? Should i open a new issue? Thanks.

**Comment by elevatebart** [comment]
Hello nicooprat, yes if you think it’s a bug you should. And I believe this is a bug in our scoped polyfill.

**Pull request merged**
