### PR TITLE
feat: enhancePreviewApp option

### LINKED ISSUE #1381: Allow users to enhance the Vue app instance in vue 3
This is a follow up to #125

I will need to add another option: `enhancePreviewApp`.

Here is how you will use it:

```js
// styleguide.config.js
import { defineConfig } from 'vue-styleguidist'

export default defineConfig({
  enhancePreviewApp: 'styleguide/enhanceApp.js' // path of the file you want to define directives in
})
```

```js
// styleguide/enhanceApp.js
import directive from '@/directives'
import { defineEnhanceApp } from 'vue-styleguidist'

export default defineEnhanceApp((app) => {
  app.directive('directive', directive)
})
```

### PR DESCRIPTION
**Pull request by elevatebart**
closes #1381 

- [x] Write docs
- [x] Make example

### CODE REVIEW

**Comment by didagu** [comment]
will there be any new version for "vue-cli-plugin-styleguidist" ? @elevatebart

**Comment by elevatebart** [comment]
There should be no need for an explicit new version since etc semantic versioning of the plugin includes the current version of VSG.

run this if you are using npm 

```bash
npm update --save vue-styleguidist
```

or this if you use yarn

```bash
yarn upgrade vue-styleguidist
```

or pnpm 

```bash
pnpm up vue-styleguidist
```

**Comment by didagu** [comment]
I think there was a typo in the 'enhancePreviewApp' documentation. It is written ```export default (app)``` instead of ```export default defineEnhanceApp((app) => { ... })``` @elevatebart 

Selection_177

**Comment by didagu** [comment]
I tried using the new enhancePreviewApp feature but I get this error @elevatebart 
Selection_177
.

This is my styleguide.config.js

```
const { BundleAnalyzerPlugin } = require('webpack-bundle-analyzer');
const { defineConfig } = require('vue-styleguidist');

const docSiteUrl = process.env.DEPLOY_PRIME_URL || 'https://vue-styleguidist.github.io';

const path = require('path');

const cliPath = require.resolve('@vue/cli-service');
console.log(path.dirname(cliPath));
const webpackPath = require.resolve('webpack', { paths: [path.dirname(cliPath)] });
process.env.VSG_WEBPACK_PATH = webpackPath;

module.exports = defineConfig({
  // set your styleguidist configuration here
  title: 'Default Style Guide',
  enhancePreviewApp: path.join(__dirname, 'styleguide/global.requires.js'),
  defaultExample: true,
  components: 'src/components/**/[A-Z]*.vue',
  ribbon: {
    text: 'Back to examples',
    url: `${docSiteUrl}/Examples.html`,
  },
  styleguideDir: 'dist',
  webpackConfig: {
    plugins: process.argv.includes('--analyze') ? [new BundleAnalyzerPlugin()] : [],
  },
  codeSplit: true,
  minimize: false,
  skipComponentsWithoutExample: true,
});
```

and this is my global.requires.js file

```
import { defineEnhanceApp } from 'vue-styleguidist';
import VueObserveVisibility from 'vue3-observe-visibility';
import { VTooltip } from 'floating-vue';
import loadable from '../src/directives/loadable';
import helpable from '../src/directives/helpable';

export default defineEnhanceApp((app) => {
  app
    .directive('tooltip', VTooltip)
    .directive('observe-visibility', VueObserveVisibility)
    .directive('loadable', loadable)
    .directive('helpable', helpable);
});
```

**Comment by elevatebart** [comment]
@didagu I tried using your setup
https://github.com/elevatebart/test-app

Could not find the error except the presence of a function that does not exist yet.

**Pull request merged**
