### PR TITLE
feat: initial commit for preset package

### PR DESCRIPTION
**Pull request by JessicaSachs**

### CODE REVIEW

**Comment by elevatebart** [comment]
Argl !!! In error I pushed you...

We publish the preset in the monorepo because the CLI will hate it.
I made you a member of the organization so that you can create your own repo there.

the 2 problems with this one are
- it will try to get published through semantic release as part of the release process
- vue/cli will look for the json at the root of the repo and not find it

**Comment by JessicaSachs** [comment]
Ah. Hm, so new repository?

**Comment by elevatebart** [comment]
indeed !!

**Comment by elevatebart** [comment]
`vue-styleguidist/preset` ?

**Comment by elevatebart** [comment]
pushed on https://github.com/vue-styleguidist/preset

**Pull request closed without merging**
