### PR TITLE
docs: update CounterButton.vue in docgen example

### PR DESCRIPTION
**Pull request by TheJaredWilcurt**

### CODE REVIEW

**Comment by elevatebart** [comment]
Thank you @TheJaredWilcurt,

You are almost there...
Can you update your commit message to say:

```
docs: update CounterButton.vue in docgen example
```

Styleguidist uses commit messages to determine versions to deliver.

**Comment by TheJaredWilcurt** [comment]
I don't know how to modify a commit message after it's already been commited, you can do whatever changes you want.

**Comment by TheJaredWilcurt** [comment]
Changed the title, if that's what you meant

**Comment by elevatebart** [comment]
You can use the following command `git commit --amend` 
It will re-open your editor

**Comment by elevatebart** [comment]
Then, once you've done it you can `git push --force` to push your new commit instead of the old one.

**Pull request merged**
