### PR TITLE
Updating vue-cli-plugin to add icons and configuration options

### PR DESCRIPTION
**Pull request by JessicaSachs**
Below are the outstanding tasks to finish up work on #306 
- [x] Add the Build task config
- [x] Add the Serve tasks config
- [x] Determine what options we're going to support inside of the Configuration panel
- [x] Config panel mapping/options

### CODE REVIEW

**Comment by elevatebart** [comment]
Here is a list of all options

assetsDir
- [ ] compilerConfig
- [ ] components
- [ ] context
- [ ] contextDependencies
- [ ] configureServer
- [ ] dangerouslyUpdateWebpackConfig
- [ ] defaultExample
- [ ] getComponentPathLine
- [ ] editorConfig
- [ ] getExampleFilename
- [ ] exampleMode
- [ ] ignore
- [ ] logger
- [ ] mountPointId
- [ ] pagePerSection
- [ ] printBuildInstructions
- [ ] printServerInstructions
- [ ] previewDelay
- [ ] propsParser
- [ ] require
- [ ] renderRootJsx
- [ ] ribbon
- [ ] sections
- [ ] serverHost
- [ ] serverPort
- [ ] showSidebar
- [ ] skipComponentsWithoutExample
- [ ] styleguideComponents
- [ ] styleguideDir
- [ ] styles
- [ ] template
- [ ] theme
- [ ] title
- [ ] sortProps
- [ ] updateDocs
- [ ] updateExample
- [ ] usageMode
- [ ] verbose
- [ ] version
- [ ] webpackConfig

**Comment by JessicaSachs** [comment]
Definitely needs some "single source of truth" reconciliation of options/config, or it's gonna be a nightmare to maintain IMHO.... I'm not sure where styleguidists' list of configurations is code-wise, but the options should probably be driven from there.

**Comment by elevatebart** [comment]
The config reference you are looking for is here:

[packages/vue-styleguidist/scripts/schemas/config.js](https://github.com/vue-styleguidist/vue-styleguidist/blob/dev/packages/vue-styleguidist/scripts/schemas/config.js)

**Comment by JessicaSachs** [comment]
OK great! I'll use that to derive the prompts.

**Comment by JessicaSachs** [comment]
Do you wanna block merging on it or play another story?

**Comment by elevatebart** [comment]
I have merged in a couple of features that will help you test with the monorepo.
I think we should start with that since it works and definitely provides value.
We will expose the schema better in a further feature.

Thank you for the great work.

**Pull request merged**
