### PR TITLE
Fixing broken styles import

### PR DESCRIPTION
**Pull request by AustinGil**

### CODE REVIEW

**Comment by elevatebart** [comment]
@AustinGil thanks for the PR. That is very helpful. 
Can you also update the version of vue-live in the dependencies to 1.16?
I noticed I did the change from diet to lib between 14 and 16... sorry about that.

**Comment by AustinGil** [comment]
> @AustinGil thanks for the PR. That is very helpful.
> Can you also update the version of vue-live in the dependencies to 1.16?
> I noticed I did the change from diet to lib between 14 and 16... sorry about that.

Done!

**Review by elevatebart — APPROVED** [review]
Thank you @AustinGil 

I will try and update the vue-live readme so that no-one has to get in trouble for it again.

**Comment by AustinGil** [comment]
Hey, no worries. I was going to help with that as well, but I got distracted with trying to get things working. Im still not fully hooked up, but if I can get around to it, I will.

**Pull request merged**
