### PR TITLE
feat(core): update react styleguidist to 9.4

### PR DESCRIPTION
**Pull request by elevatebart**
- Adds support for es6 imports
- make new option simpleEditor to only load the `simple react editor` and prism.js for even smaller bundles

### CODE REVIEW

**Comment by elevatebart** [comment]
I can as well override the Editor component to bring back codemirror if you prefer.
@rafaesc what is your take on it ?

**Comment by rafaesc** [comment]
I think that we can maintain the same library of rsg, if it doesn't affect the current view

**Comment by elevatebart** [comment]
@rafaesc do you mean to have the same editor as React-Styleguidist (breaking change) or to keep CodeMirror ?

**Comment by elevatebart** [comment]
I made usage of the simpleEditor opt-in so that everyone can switch at their pace... no need for a major version.

**Comment by rafaesc** [comment]
@elevatebart  ok I see that you are still using CodeMirror, well I wanted to use Prism because there are [interesting websites](https://prismjs.com/#used-by) that use it, but its fine also CodeMirror

**Comment by elevatebart** [comment]
@rafaesc I actually want to use both. the `simpleEditor` option is now documented

**Comment by elevatebart** [comment]
@rafaesc, I removed all the fat from there. Only 2 parts to see, the addition of the new editor, code & documentation and the adaptation to the React-styleguidist folder structure (add lib/ everywhere)

**Comment by elevatebart** [comment]
And the rsg-component-default alias of course

**Pull request merged**
